import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Analysis, Component, ComponentEdge, Subgraph } from '../schema/analysis.ts';

const MAX_TOP_LEVEL_COMPONENTS = 12;
const MAX_FILES_PER_PAGE = 20;

export interface RenderOpts {
  onlyComponents?: string[];
}

function sanitizeNameForFilename(name: string): string {
  // Replace whitespace + path separators + anything outside [A-Za-z0-9_.-] with underscore.
  return name.replace(/[^A-Za-z0-9_.-]/g, '_').replace(/^_+|_+$/g, '');
}

function buildFilenameMap(components: Component[]): Record<string, string> {
  const taken = new Map<string, string>(); // baseName → owning component id
  const result: Record<string, string> = {};

  for (const c of components) {
    let base = sanitizeNameForFilename(c.name);
    if (!base) base = c.id;
    const candidate = `${base}.md`;
    if (!taken.has(candidate)) {
      taken.set(candidate, c.id);
      result[c.id] = candidate;
    } else {
      const suffixed = `${base}__${c.id}.md`;
      taken.set(suffixed, c.id);
      result[c.id] = suffixed;
    }
  }
  return result;
}

function escapeMermaidLabel(s: string): string {
  // Inside `"..."` labels: quotes need escaping; pipes and brackets break the parser.
  return s
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\|/g, '/')
    .replace(/\[/g, '(')
    .replace(/\]/g, ')');
}

function mermaidGraph(
  components: Component[],
  edges: ComponentEdge[],
  filenameMap: Record<string, string>,
  opts: { withClicks: boolean } = { withClicks: true },
): string {
  const lines: string[] = ['```mermaid', 'graph LR'];
  for (const c of components) {
    lines.push(`  ${c.id}["${escapeMermaidLabel(c.name)}"]`);
  }
  for (const e of edges) {
    lines.push(`  ${e.from} --> ${e.to}`);
  }
  if (opts.withClicks) {
    for (const c of components) {
      const file = filenameMap[c.id];
      if (file) lines.push(`  click ${c.id} href "./${file}" "Details"`);
    }
  }
  lines.push('```');
  return lines.join('\n');
}

function fileListBlock(files: string[]): string {
  if (files.length <= MAX_FILES_PER_PAGE) {
    return files.map((f) => `- \`${f}\``).join('\n');
  }
  const head = files.slice(0, MAX_FILES_PER_PAGE);
  const remaining = files.length - MAX_FILES_PER_PAGE;
  return head.map((f) => `- \`${f}\``).join('\n') + `\n- _Other (${remaining} files)_`;
}

function renderOverview(analysis: Analysis, filenameMap: Record<string, string>): string {
  const projectName = analysis.project.name;
  const dateLine = analysis.generated_at.slice(0, 10);
  const out: string[] = [];
  out.push(`# ${projectName} — Architecture overview`);
  out.push('');
  out.push(`> Generated by compass on ${dateLine}. Re-run with \`/compass-refresh\`.`);
  out.push('');
  out.push(mermaidGraph(analysis.components, analysis.edges, filenameMap, { withClicks: true }));
  out.push('');
  for (const c of analysis.components) {
    out.push(`## ${c.name}`);
    if (c.description) out.push(c.description);
    out.push(`*Why this grouping: ${c.rationale}*`);
    out.push(`→ [${filenameMap[c.id]}](./${filenameMap[c.id]})`);
    out.push('');
  }
  return out.join('\n');
}

function renderComponentPage(
  c: Component,
  analysis: Analysis,
  filenameMap: Record<string, string>,
): string {
  const out: string[] = [];
  out.push(`# ${c.name}`);
  out.push('');
  if (c.description) {
    out.push(c.description);
    out.push('');
  }
  out.push(`*Why this grouping: ${c.rationale}*`);
  out.push('');
  out.push(`**Confidence:** ${c.confidence}`);
  out.push('');
  out.push('## Files');
  out.push(fileListBlock(c.files));
  out.push('');
  if (c.symbols.length > 0) {
    out.push('## Symbols');
    out.push(c.symbols.map((s) => `- \`${s}\``).join('\n'));
    out.push('');
  }
  const sub: Subgraph | undefined = analysis.subgraphs[c.id];
  if (sub && sub.components.length > 0) {
    out.push('## Internal structure');
    out.push('');
    out.push(mermaidGraph(sub.components, sub.edges, {}, { withClicks: false }));
    out.push('');
    for (const sc of sub.components) {
      out.push(`### ${sc.id} — ${sc.name}`);
      if (sc.rationale) out.push(`*${sc.rationale}*`);
      if (sc.files.length > 0) out.push(fileListBlock(sc.files));
      out.push('');
    }
  }
  return out.join('\n');
}

/**
 * SPEC §5.4 — write overview.md and one .md per component into outDir.
 *  - 12-component top-level cap (Open Q5) — refuses to render above
 *  - 20-file per-component cap with "Other (N files)" bucket
 *  - filename collisions resolved by suffixing with __<id>
 *  - opts.onlyComponents limits per-component re-renders (incremental mode)
 */
export function renderAnalysis(analysis: Analysis, outDir: string, opts: RenderOpts = {}): void {
  if (!analysis.components || analysis.components.length === 0) {
    throw new Error('renderAnalysis: refusing to render an empty components list');
  }
  if (analysis.components.length > MAX_TOP_LEVEL_COMPONENTS) {
    throw new Error(
      `renderAnalysis: ${analysis.components.length} top-level components exceed the cap of ${MAX_TOP_LEVEL_COMPONENTS} (SPEC Open Q5) — the critique pass should have merged sparse clusters`,
    );
  }
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  const filenameMap = buildFilenameMap(analysis.components);

  // overview always re-rendered (one per command run)
  writeFileSync(join(outDir, 'overview.md'), renderOverview(analysis, filenameMap));

  const only = opts.onlyComponents ? new Set(opts.onlyComponents) : null;
  for (const c of analysis.components) {
    if (only && !only.has(c.id)) continue;
    writeFileSync(join(outDir, filenameMap[c.id]), renderComponentPage(c, analysis, filenameMap));
  }
}
